### ISSUE TITLE
Still white

### ISSUE THREAD

**Issue by axelgunn** [vip32/Hangfire.Dashboard.Dark#1] opened 2017-02-13 11:43 UTC
Hi

I am using .net Core but after adding the extension and configuring startup.cs by dashboard is still white.
            services.AddHangfire(config =>
            {
                config.UseSqlServerStorage(sConnectionString);
                config.UseConsole();
                config.UseRecurringJob("recurringjob.json");
                config.UseRecurringJob(typeof(RecurringJobService));
                config.UseDefaultActivator();
                **config.UseDarkDashboard();**
            });

These are my dependencies:
        "Hangfire.AspNetCore": "1.6.8",
        "Hangfire.Core": "1.6.8",
        "Hangfire.SqlServer": "1.6.8",
        "Hangfire.Console": "1.2.0",
        "Hangfire.RecurringJobExtensions": "1.1.6",
        "Hangfire.Dashboard.Authorization": "2.1.0",
        "Hangfire.Dashboard.Dark": "1.0.6"

Is version 1.6.8 incompatible with 1.0.6 or is it something else ?

[UPDATE]

Downgraded to Hangfire.Core 1.6.0 and it works. Next question: Where can I set it to work with 1.6.8  and onward?

**Comment by vip32** [comment] 2017-02-24 17:25
Strange, i use 1.6.8 too and it is dark. However i am not on .core (4.6.1)

**Comment by axelgunn** [comment] 2017-03-29 19:39
Solved itself with the lates Hangfire update

**Comment by zzyykk123456** [comment] 2017-11-14 08:59
It is white .My Console APP is based on .net framework 4.6.2  and Hangfire.Core is 1.6.17

**Comment by bryancrosby** [comment] 2018-01-18 16:20
Verified that it does not work on 1.6.17 as well. Target .NET Framework 4.6 and Hangfire.Core is 1.6.17

**Comment by vip32** [comment] 2018-01-21 10:40
Do you have a fix or PR?

**Comment by bryancrosby** [comment] 2018-01-22 20:35
@vip32 I think the issue is that `EmbeddedResourceDispatcher` is now marked internal. Probably would have to do some hacky reflection to get it to work

**Comment by jfantunes** [comment] 2020-05-16 05:33
Is there going to be a fix for this. I can't use it it's still white

**Comment by vip32** [comment] 2020-05-18 07:16
sorry, currently not working on this. please prepare a PR

**Closed as completed** 2020-11-13 09:40 UTC
